version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb2"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    volumes:
      - ./mongodb2:/data/db