# Generated by Django 3.0.5 on 2021-04-05 03:05

import company.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coNm', models.CharField(max_length=250)),
                ('coAddr', models.CharField(max_length=250)),
                ('regionCd', models.IntegerField()),
                ('regionNm', models.CharField(max_length=250)),
                ('superIndTpCd', models.IntegerField()),
                ('superIndTpNm', models.CharField(max_length=250)),
                ('coContent', models.TextField()),
                ('coMainProd', models.CharField(max_length=250)),
                ('coGdpnt', models.CharField(max_length=250)),
                ('coHomePage', models.CharField(max_length=250)),
                ('alwaysWorkerCnt', models.CharField(max_length=250)),
                ('sgBrandNm', djongo.models.fields.ArrayField(model_container=company.models.Certified)),
                ('info', djongo.models.fields.EmbeddedField(model_container=company.models.Info, null=True)),
            ],
        ),
    ]
